### ISSUE TITLE
Error: Header CRC

### ISSUE THREAD

**Issue by EmmettVA** [ApacheThunder/NTR_Launcher#11]

**Comment by ApacheThunder** [comment]
You need to specify which flashcart(s) this error showed up for.

**Comment by ApacheThunder** [comment]
Due to lack of further information I will have to close this issue.

**Comment by LazaroFilm** [comment]
I get this issue as well when tapping on the `NTR Launcher Slot-1 launcher Apache Thunder & RocketRobz` icon. The screens go black, then white. Then the error message shows in red.

**Comment by Masamune3210** [comment]
....ON WHAT though

**Comment by Laxan3000** [comment]
Having the same issue;
Flashcard I have is a clone of another, but using YSMenu / DSpico from this link makes it work on a regular DS: https://sanrax.github.io/flashcart-guides/cart-guides/v2_10T/

@ApacheThunder
