### ISSUE TITLE
M3DS REAL don't boot

### ISSUE THREAD

**Issue by malekairmaroc7** [ApacheThunder/NTR_Launcher#3]
Hey. Can you fix booting into M3DS real? I just get a white screen.
Thank you

**Comment by AngryKiller** [comment]
Same on my DSi :/

**Comment by malekairmaroc7** [comment]
Nevermind. I got it to work without NTR Launcher😁
EDIT: Do you have a M3DS Real Flashcard, too? @AngryKiller

**Comment by AngryKiller** [comment]
Yes I do

**Comment by malekairmaroc7** [comment]
Which firmware version is the best for you?

**Comment by AngryKiller** [comment]
What do you mean? The best M3 Cart?

**Comment by malekairmaroc7** [comment]
Nevermind. Do you know why I get a Black screen when using cheat codes for ACWW?

**Comment by ApacheThunder** [comment]
Unfortunately I can not fix boot issues with cards I do not own. Good to hear you found a way to boot it though. :D

**Comment by ApacheThunder** [comment]
To update this thread I recently acquired a M3 DS Real and last I checked the latest versions (2.6 and 2.7) can boot this cart.. Although on a HiyaCFW DSi, it boots fine from system menu. You will only need NTR Launcher on 3DS in that case.
