### ISSUE TITLE
Still working with 3ds v11.15.0-47

### ISSUE THREAD

**Issue by saint-etienne** [ApacheThunder/NTR_Launcher#9]
Hi apache, does ntr launcher/stage2 launchers work with the newest 3ds update?

**Comment by DraconicNEO** [comment]
> 
> 
> Hi apache, does ntr launcher/stage2 launchers work with the newest 3ds update?

I think it does @lifehackerhansol tested it out on their 3DS, although I don't think it works on New 3DS Models though, I tested it on my 2DS XL and it didn't boot.

**Comment by saint-etienne** [comment]
> > Hi apache, does ntr launcher/stage2 launchers work with the newest 3ds update?
> 
> I think it does @lifehackerhansol tested it out on their 3DS, although I don't think it works on New 3DS Models though, I tested it on my 2DS XL and it didn't boot.

Ah, really? Which flashcart did you use? _(Is it perfectly working before you updated to 11.15?)_

**Comment by DraconicNEO** [comment]
> 
> 
> > > Hi apache, does ntr launcher/stage2 launchers work with the newest 3ds update?
> > 
> > 
> > I think it does @lifehackerhansol tested it out on their 3DS, although I don't think it works on New 3DS Models though, I tested it on my 2DS XL and it didn't boot.
> 
> Ah, really? Which flashcart did you use? _(Is it perfectly working before you updated to 11.15?)_

R4i SDHC 2021 and R4i 3DS. Both give a White screen in NTR Launcher.

**Comment by renolc** [comment]
I have an EDGE cart that is also giving a white screen. I just got this n2ds xl so I didn't have it before 11.15 to test

**Comment by saint-etienne** [comment]
> R4i SDHC 2021 and R4i 3DS. Both give a White screen in NTR Launcher.

Both are newer flashcarts. They should work w/o NTR. You can uninstall the launcher & test the R4s again.

**Comment by saint-etienne** [comment]
> I have an EDGE cart that is also giving a white screen. I just got this n2ds xl so I didn't have it before 11.15 to test

This dude said it does:
[Edge works Perfect with NTRLauncher on new 3dsxl, thanks.
](https://gbatemp.net/threads/edge-3ds-compatibility.540817/#post-9019387) 

You can try this instead: [R4 Stage2 TWL Flashcart Launcher](https://gbatemp.net/threads/r4-stage2-twl-flashcart-launcher-and-perhaps-other-cards-soon.416434/)

**Comment by lifehackerhansol** [comment]
It's funny how NTR Launcher was supposed to supersede all of them and failed. Pretty sure NTR Launcher on legacy mode using a self-compiled build does work.
